# Generated by Django 3.1.3 on 2020-11-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='event date')),
                ('time', models.TimeField(verbose_name='event time')),
                ('name', models.CharField(max_length=50, verbose_name='event name')),
                ('attending', models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL, verbose_name='attendees')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='event creator')),
                ('hosts', models.ManyToManyField(related_name='events_hosting', to=settings.AUTH_USER_MODEL, verbose_name='event hosts')),
                ('invited', models.ManyToManyField(related_name='events_invited_to', to=settings.AUTH_USER_MODEL, verbose_name='invitees')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.location', verbose_name='event location')),
            ],
        ),
    ]
