# Generated by Django 3.1.3 on 2020-11-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='event date')),
                ('time', models.TimeField(verbose_name='event time')),
                ('description', models.TextField(verbose_name='event description')),
                ('attending', models.ManyToManyField(related_name='events_attending', to='accounts.User', verbose_name='attendees')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to='accounts.user', verbose_name='event creator')),
                ('hosts', models.ManyToManyField(related_name='events_hosting', to='accounts.User', verbose_name='event hosts')),
                ('invited', models.ManyToManyField(related_name='events_invited_to', to='accounts.User', verbose_name='invitees')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.location', verbose_name='event location')),
            ],
        ),
    ]
