version: '3.8'

services: 
  web:
    build: ./
    image: top-private-events:compose
    command: python manage.py runserver 0.0.0.0:8080
    ports: 
      - 8000:8080
    env_file: 
      - ./.env.dev
