# Generated by Django 3.1.3 on 2020-11-24 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='event name')),
                ('description', models.TextField(null=True, verbose_name='event description')),
                ('date', models.DateField(verbose_name='event date')),
                ('time', models.CharField(max_length=50, verbose_name='event time')),
                ('location', models.CharField(max_length=100, verbose_name='event location')),
                ('attending', models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL, verbose_name='attendees')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='event creator')),
                ('hosts', models.ManyToManyField(related_name='events_hosting', to=settings.AUTH_USER_MODEL, verbose_name='event hosts')),
                ('invited', models.ManyToManyField(related_name='events_invited_to', to=settings.AUTH_USER_MODEL, verbose_name='invitees')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
